spring:
  datasource:
    url: jdbc:h2:mem:changedb;DB_CLOSE_DELAY=-1
    username: root
    password: sasa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
